//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncChat.WindowsForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsyncChat.WindowsForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account cannot be created, please try again..
        /// </summary>
        internal static string Error_AccountCannotBeCreated {
            get {
                return ResourceManager.GetString("Error_AccountCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account cannot be created.
        /// </summary>
        internal static string Error_Title_AccountCannotBeCreated {
            get {
                return ResourceManager.GetString("Error_Title_AccountCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account was created successfully..
        /// </summary>
        internal static string Information_AccountCreated {
            get {
                return ResourceManager.GetString("Information_AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created.
        /// </summary>
        internal static string Information_Title_AccountCreated {
            get {
                return ResourceManager.GetString("Information_Title_AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PersonAdd {
            get {
                object obj = ResourceManager.GetObject("PersonAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerCordGreen {
            get {
                object obj = ResourceManager.GetObject("PowerCordGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerCordRed {
            get {
                object obj = ResourceManager.GetObject("PowerCordRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter an email..
        /// </summary>
        internal static string Warning_EmptyEmail {
            get {
                return ResourceManager.GetString("Warning_EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a server address..
        /// </summary>
        internal static string Warning_EmptyIpAddress {
            get {
                return ResourceManager.GetString("Warning_EmptyIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter your name..
        /// </summary>
        internal static string Warning_EmptyName {
            get {
                return ResourceManager.GetString("Warning_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter your password..
        /// </summary>
        internal static string Warning_EmptyPassword {
            get {
                return ResourceManager.GetString("Warning_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered a wrong name or password..
        /// </summary>
        internal static string Warning_IncorrectCredentials {
            get {
                return ResourceManager.GetString("Warning_IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty email.
        /// </summary>
        internal static string Warning_Title_EmptyEmail {
            get {
                return ResourceManager.GetString("Warning_Title_EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty IP server address.
        /// </summary>
        internal static string Warning_Title_EmptyIpAddress {
            get {
                return ResourceManager.GetString("Warning_Title_EmptyIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty name.
        /// </summary>
        internal static string Warning_Title_EmptyName {
            get {
                return ResourceManager.GetString("Warning_Title_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty password.
        /// </summary>
        internal static string Warning_Title_EmptyPassword {
            get {
                return ResourceManager.GetString("Warning_Title_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect credentials.
        /// </summary>
        internal static string Warning_Title_IncorrectCredentials {
            get {
                return ResourceManager.GetString("Warning_Title_IncorrectCredentials", resourceCulture);
            }
        }
    }
}
